version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  heroku: circleci/heroku@1.2.6

executors:
  node-image:
    docker:
      - image: cimg/node:12.22

jobs:
  unit-tests:
    executor: node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test:cov
      - codecov/upload:
          file: './coverage/cobertura-coverage.xml'

  publish-package:
    executor: node-image
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Publish package
          command: npm publish
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-demo:
    executor: node-image
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: heroku-v1
      - heroku/install
      - save_cache:
          paths:
            - ~/usr/local/bin/heroku
          key: heroku-v1
      - run:
          name: Build demo app
          command: npm run build:app
      - run:
          name: Create git repo
          command: cd demo-app && git init && git config user.email "$GIT_EMAIL" && git config user.name "$GIT_NAME"
      - run:
          name: Commit files
          command: cd demo-app && git add . && git commit -m"Deploy $CIRCLE_TAG"
      - run:
          name: Push to Heroku
          command: cd demo-app && git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master -f

workflows:
  version: 2
  test:
    jobs:
      - unit-tests:
          filters:
            tags:
              ignore: /.*/
  deploy:
    jobs:
      - publish-package:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-demo:
          requires:
            - publish-package
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
