version: 2.1

executors:
  node-image:
    docker:
      - image: cimg/node:12.22

jobs:
  unit-tests:
    executor: node-image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test:cov

workflows:
  version: 2
  test:
    jobs:
      - unit-tests
